# Change these first
owner: smartmanru # Your GitHub organization or username, where this repository lives
repo: site_availability # The name of this repository
hh: $HH
rout: $ROUTER
plprox: $PL_PROXY
sites:
  - name: home_hh
    url: https://$HH
  - name: router
    url: https://$ROUTER
  - name: Vw
    url: https:/$VW
  - name: ShortLink
    url: http://$SHORT

  

status-website:
  # theme: default
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: sites.shtxt.info
  # baseUrl: sites.shtxt.info
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Smartman Sites
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
